#!/usr/bin/env bash

# Function to display information for a specific subdomain
display_info() {
    domain="$1"
    subdomain="$2"

    # Use dig to get information about the subdomain
    result=$(dig "$subdomain.$domain" +short)

    # Check if the result is empty
    if [ -z "$result" ]; then
        echo "The subdomain $subdomain does not exist for $domain"
    else
        record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
        echo "The subdomain $subdomain is a $record_type record and points to $result"
    fi
}

# Function to display information for default subdomains
display_default_info() {
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")

    for subdomain in "${subdomains[@]}"; do
        display_info "$domain" "$subdomain"
    done
}

# Check the number of arguments
if [ "$#" -eq 1 ]; then
    display_default_info "$1"
elif [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
