#!/usr/bin/env bash
# Takes 'domain' and 'subdomain' parameters and displays information for the specified subdomain

print_info() {
    local domain="$1"
    local subdomain="$2"
    local query_result=$(dig "$subdomain.$domain" +short)

    if [ -z "$query_result" ]; then
        echo "The subdomain $subdomain does not exist for $domain"
    else
        local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
        echo "The subdomain $subdomain is a $record_type record and points to $query_result"
    fi
}

if [ "$#" -eq 2 ]; then
    print_info "$1" "$2"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_info "$1" "$subdomain"
    done
fi
