#!/usr/bin/env bash
# This script manages the manage_my_process script

case "$1" in
    start)
        if [ ! -f /var/run/my_process.pid ]; then
            ./manage_my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process started"
        else
            echo "manage_my_process is already running"
        fi
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
        fi
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
