#!/usr/bin/env bash
# A script that displays Best School 10 times using for

for ((i = 1; i <= 10; i++))
do
    echo "Best School"
don#!/usr/bin/env bash
# A script that displays Best School 10 times using while

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    ((i++))
done
