#!/bin/bash

# Update package lists to ensure we have the latest information
sudo apt update

# Install ufw if not already installed
sudo apt install ufw -y

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22), HTTPS (port 443), and HTTP (port 80) traffic
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw --force enable
