#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
# **** localhost resolves to 127.0.0.2
# **** facebook.com resolves to 8.8.8.8

sudo sed -i '/^127.0.0.1[[:space:]]\+localhost/ s/$/ 127.0.0.2/' /etc/hosts
sudo sed -i '/facebook\.com/ s/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/8.8.8.8/' /etc/hosts
