#!/usr/bin/env bash

# Set the key file name
key_name="school"

# Set the number of bits for the key
key_bits=4096

# Set the passphrase
passphrase="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $key_bits -f "$key_name" -N "$passphrase"

# Provide user feedback
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $key_name."
echo "Your public key has been saved in $key_name.pub."
